### ISSUE TITLE
Adding a todo creates an endless loop. 

### ISSUE THREAD

**Issue by dreyn74** [PolymerLabs/todo-list#1]
When I try to add a todo, the program creates an infinite number of entries of that todo into my firebase.

**Comment by robdodson** [comment]
Hm that should be fixed by the current dependencies in `bower.json` (note that I had to depend on Polymer master because linking multiple paths in todo-data is a new feature). I'll do a fresh checkout and see if i can recreate the error.

**Comment by dreyn74** [comment]
Hi Rob,
I didn't bother with updating dependencies before trying the to do list. I
will update the dependencies and get that straightened out.

Thanks,

Dan

**Comment by dreyn74** [comment]
Updating dependencies worked!

**Comment by robdodson** [comment]
Ah great, glad to hear it :) It should be fixed in the next release of polymer
