### ISSUE TITLE
elements.html is 790KB

### ISSUE THREAD

**Issue by kellerapps** [PolymerLabs/todo-list#18]
[The youtube webinar](https://www.youtube.com/watch?v=fD2As5RmM8Q) notes the small size of polymer core (40KB here) so is .8MB surprising for this small app? Sorry if this is the wrong place to mention this.

**Comment by robdodson** [comment]
Those numbers refer to the minified/gzipped size of Polymer. The total app is 194kb over the wire.

<img width="320" alt="screen shot 2016-04-08 at 10 08 27 am" src="https://cloud.githubusercontent.com/assets/1066253/14391604/e1f747ce-fd71-11e5-9557-90cac66488c2.png">

**Comment by robdodson** [comment]
https://polymer-todo.firebaseapp.com/

**Comment by kellerapps** [comment]
| proj | elements.html (KB) | zip (KB) |
| --- | --: | --: |
| todo | 800 | 200 |
| psk | 570 | 140 |

polymer-todo.firebaseapp.com loads elements.vulcanized.html while the repo loads elements.html. 

---

polymer-todo.firebaseapp.com shows toast while repo doesn't (it didn't breakpoint in app.js/displayInstalledToast()). 

If I reload index.html, a console msg appears about bootstrap-sw-toolbox-setup.js.

README says to add precache but gulpfile says to add cache-config.

**Comment by robdodson** [comment]
> polymer-todo.firebaseapp.com loads elements.vulcanized.html while the repo loads elements.html.

Try running `gulp serve:dist`. I believe that will give you the productionized version. Just running `gulp serve` produces a debug build.

For the other issues, I haven't updated this project in a little while, probably is due for a house cleaning.

**Comment by kellerapps** [comment]
No serve:dist doesn't either. 

useref is using the old syntax.

platinum-sw-cache refs precache.json but gulpfile generates cache-config.json. Perhaps gulpfile should do some asserting.
