### ISSUE TITLE
Can't Sign Out

### ISSUE THREAD

**Issue by dreyn74** [PolymerLabs/todo-list#2]
When I try to sign out, the console logs, 'listener method `signOut` not defined'

**Comment by robdodson** [comment]
Yep that's a feature I need to add in

**Comment by aguimaraes** [comment]
Hello Rob.
I'm new on Polymer and I'm trying to implement the logout functionality.
I'm trying to call the signOut method of the todo-data element from app.js, but this.ref is always undefined.
Can you explain me why?
I don't know if this is the right place to ask, sorry if it is wrong.

That's how I'm calling it: document.querySelector("#my-data").signOut();

The querySelector returns the element and signOut is called, but ref is undefined.

**Comment by robdodson** [comment]
Should be fixed in https://github.com/PolymerLabs/todo-list/commit/1d2a90f232b0e6f9cea560c0b8a38967bad355f9
