### ISSUE TITLE
Error when editing/delete new element

### ISSUE THREAD

**Issue by zohon** [PolymerLabs/todo-list#4]
i have take the example of todo with https://noteplaces.firebaseio.com/

and i can edit and delete element if they are loaded form firebase but when i create a new one i cannot edit it or delete it unless i reload the page

this is the first error i get when i try to edit after the creation :

Uncaught Error: Firebase.child failed: First argument was an invalid path: "undefined". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]" firebase-debug.js:8749

and when i try again i got this one : 

Uncaught Error: Firebase.child failed: First argument was an invalid path: "null". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]" firebase-debug.js:8749

i think i lost the link with firebase for my item but i cannot see where is it an error from my firebase ?

**Comment by robdodson** [comment]
I'm not able to view your firebase instance. If you directly cloned the source then it's trying to write to a user's object on Firebase. Do you see that users object being created in the firebase instance?

**Comment by zohon** [comment]
i redo all my work and take a copy of todo.
i was not using user connection for my project so i had to comment it.

now all work find will look later for the issue but the issue is ok for me thanks for your time.

Hope to share my project later. polymer + firebase is awesome.

thanks to polymer and firebase team for the work. hope to work with it for professional project :D

**Comment by juliusknth** [comment]
Hi Rob and Zohon, I am facing kind of the same issue as the above here is a link to my app https://github.com/juliusknth/e-bima-fire-fire

**Comment by evanomondi** [comment]
Sorry I have the same issue. @zohon and @robdodson  I dont understand how this was solved

**Comment by zohon** [comment]
For my part i was using firebase element without all other libs. after that
i take the todo examples of rob dodson and go from here.
I was not able to identify the issue with my first code but when using the
todo example all worked fine.

I think i was lacking an element to make it work will look to found the
issue.

Sorry for not helping you more

2015-10-13 19:45 GMT+02:00 evanomondi notifications@github.com:

**Comment by evanomondi** [comment]
thanks. found the solution here https://github.com/PolymerLabs/todo-list/issues/3
