### ISSUE TITLE
todo-input.html does not contain import of paper-input?

### ISSUE THREAD

**Issue by WaverleyDesign** [PolymerLabs/todo-list#7]
I don't know.. Is this how it is supposed to be?
https://github.com/PolymerLabs/todo-list/blob/master/app/elements/todo-input/todo-input.html#L12

**Comment by ebidel** [comment]
Yes, it should. Want to submit a PR?

**Comment by robdodson** [comment]
Fixed by https://github.com/PolymerLabs/todo-list/pull/10
